version: "3.9"
# TODO Reset passwords and remove outcommented ports

volumes:
  eb_postgresql_data: {}
  eb_caddy_data: {}

networks:
  easy_backend_service:
    name: easy_backend_service
    driver: bridge

services:
  eb-postgresql:
    container_name: eb-postgresql
    build:      
      context: .
      dockerfile: DOCKERFILE_POSTGRES
    networks:
      - easy_backend_service
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=easybackend
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - eb_postgresql_data:/var/lib/postgresql/data

  eb-keycloak:
    container_name: eb-keycloak
    image:  quay.io/keycloak/keycloak:19.0.2-legacy
    networks:
      - easy_backend_service
    environment:
      - KEYCLOAK_LOGLEVEL=ERROR
      - ROOT_LOGLEVEL=ERROR
      - TZ=Europe/Berlin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=eb-postgresql
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=changeThis
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_IMPORT=/root/realm.json
      - JDBC_PARAMS=useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./realm.json:/root/realm.json

  eb-easybackend:
    container_name: eb-easybackend
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    image: easybackend
    networks:
      - easy_backend_service

  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - eb_caddy_data:/data
      - ./cert.pem:/etc/caddy/cert.pem
      - ./key.pem:/etc/caddy/key.pem
    ports:
      - 443:443
      - 80:80
    networks:
      - easy_backend_service
